name: Update Images Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno alle 00:00
  workflow_dispatch:      # Permette di eseguire manualmente il workflow

jobs:
  update_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4

      - name: Run update script
        run: python update-photos.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add index.html
          git commit -m "Update images" || exit 0
          git push
